// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"TkoolMV_PluginCommandBook","status":true,"description":"プラグインコマンド集","parameters":{"制御文字の拡張":"はい","スクリプトに制御文字適用":"いいえ"}},
{"name":"MadeWithMv","status":false,"description":"メイン画面へ進む前に、\"Made with MV\"のスプラッシュ画面もしくはカスタマイズされたスプラッシュ画面を表示します。","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"UR65_SmartPhoneUI","status":true,"description":"スマホ用UI  ver 1.0.0\nUIのサイズをスマートフォン向けに最適化します。","parameters":{"タイトル":"1","メニュー":"1","アイテム":"1","スキル":"1","装備":"1","オプション":"1","ゲーム終了":"1","戦闘":"0","ショップ":"1","イベント関係":"0","アイコン位置修正":"1"}},
{"name":"ChangeWindowTouchPolicy","status":true,"description":"ウィンドウタッチ仕様変更プラグイン","parameters":{"枠外タッチ動作":"キャンセル"}},
{"name":"DTextPicture","status":true,"description":"動的文字列ピクチャ生成プラグイン","parameters":{}},
{"name":"SmartPath","status":true,"description":"イベントもしくはプレイヤーに、高度な経路探索を提供します。","parameters":{}},
{"name":"MPP_MoveRouteEX","status":true,"description":"【ver.1.0】移動ルートに関するコマンド詰め合わせ。","parameters":{"Search Limit":"8"}},
{"name":"MKR_MapScrollFix","status":true,"description":"(v1.0.0) 指定したスイッチがONの間、マップスクロールを固定します。","parameters":{"Default_Scroll_Fix_Sw":"10"}},
{"name":"TMEventClick","status":true,"description":"イベントをクリックして起動、ドラッグで移動させる機能を\n追加します。","parameters":{"dropStart":"0","noDropRegions":"","canMultipleDrop":"0","lockTurnEnabled":"0"}},
{"name":"ALICE_reversal_eventidXy","status":true,"description":"指定位置の情報取得を反転したバージョン","parameters":{}},
{"name":"DevToolsManage","status":true,"description":"デベロッパツール管理プラグイン","parameters":{"開始時に起動":"ON","常に前面表示":"OFF","デベロッパツール表示位置":"0,0,800,600","最小化切替キー":"F8","リロードキー":"F12","画面の左寄せキー":"F11","高速化切替キー":"F10","強制戦闘勝利キー":"F7","FPS表示":"OFF","タイトルカット":"OFF","高速開始":"OFF"}},
{"name":"CharacterPopupDamage","status":true,"description":"キャラクターのダメージポッププラグイン","parameters":{"効果音演奏":"ON","X座標補正":"0","Y座標補正":"0","HP自動ポップアップ":"ON","MP自動ポップアップ":"ON","TP自動ポップアップ":"ON","増加自動ポップアップ":"ON","減少自動ポップアップ":"ON","MPダメージ音":"","回転":"OFF","X方向半径":"0","Y方向半径":"40","回転速度":"60","拡大率":"100","拡大率変化値":"0","最前面表示":"ON"}},
{"name":"Exhydra_CharacterExtras","status":true,"description":"Options to apply various properties to characters and events.","parameters":{}}
];
